<?xml version="1.0"?>
<!DOCTYPE departures [
<!ELEMENT departures (generated, stop*)>
	<!ELEMENT generated (#PCDATA)>
		<!ATTLIST generated timezone CDATA #REQUIRED>
	<!ELEMENT stop (id, name, departure*)>
		<!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
		<!ELEMENT departure (edt, sdt, dev, text, route, dir)>
			<!ATTLIST departure mode (route|destination) #REQUIRED>
            <!ELEMENT edt (#PCDATA)>
            <!ELEMENT sdt (#PCDATA)>
            <!ELEMENT dev (#PCDATA)>
            <!ELEMENT text (#PCDATA)>
            <!ELEMENT route (id, name)>
            <!ELEMENT dir (#PCDATA)>
]>

<departures><generated timezone="-9">2015-09-19 13:11</generated><stop><id>1437</id><name>BAXTER and NORTHERN LIGHTS</name><departure mode="destination"><edt>14:01</edt><sdt>14:01</sdt><dev>0</dev><text>1 MULDOON</text><route><id>1</id><name>CROSSTOWN</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:01</edt><sdt>15:01</sdt><dev>0</dev><text>1 MULDOON</text><route><id>1</id><name>CROSSTOWN</name></route><dir>I</dir></departure><departure mode="destination"><edt>16:03</edt><sdt>16:03</sdt><dev>0</dev><text>1 MULDOON</text><route><id>1</id><name>CROSSTOWN</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:26</edt><sdt>13:26</sdt><dev>0</dev><text>1 DIMOND CENTER</text><route><id>1</id><name>CROSSTOWN</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:26</edt><sdt>14:26</sdt><dev>0</dev><text>1 DIMOND CENTER</text><route><id>1</id><name>CROSSTOWN</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:26</edt><sdt>15:26</sdt><dev>0</dev><text>1 DIMOND CENTER</text><route><id>1</id><name>CROSSTOWN</name></route><dir>O</dir></departure></stop><stop><id>1438</id><name>LAKE OTIS and TUDOR</name><departure mode="destination"><edt>13:38</edt><sdt>13:34</sdt><dev>245</dev><text>2 DOWNTOWN</text><route><id>2</id><name>LAKE OTIS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:34</edt><sdt>14:34</sdt><dev>0</dev><text>2 DOWNTOWN</text><route><id>2</id><name>LAKE OTIS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:34</edt><sdt>15:34</sdt><dev>0</dev><text>2 DOWNTOWN</text><route><id>2</id><name>LAKE OTIS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:03</edt><sdt>14:03</sdt><dev>0</dev><text>2 DIMOND CENTER</text><route><id>2</id><name>LAKE OTIS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:03</edt><sdt>15:03</sdt><dev>0</dev><text>2 DIMOND CENTER</text><route><id>2</id><name>LAKE OTIS</name></route><dir>O</dir></departure><departure mode="destination"><edt>16:03</edt><sdt>16:03</sdt><dev>0</dev><text>2 DIMOND CENTER</text><route><id>2</id><name>LAKE OTIS</name></route><dir>O</dir></departure></stop><stop><id>1439</id><name>LAKE OTIS and ABBOTT</name><departure mode="destination"><edt>13:28</edt><sdt>13:24</sdt><dev>245</dev><text>2 DOWNTOWN</text><route><id>2</id><name>LAKE OTIS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:24</edt><sdt>14:24</sdt><dev>0</dev><text>2 DOWNTOWN</text><route><id>2</id><name>LAKE OTIS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:24</edt><sdt>15:24</sdt><dev>0</dev><text>2 DOWNTOWN</text><route><id>2</id><name>LAKE OTIS</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:13</edt><sdt>13:13</sdt><dev>0</dev><text>2 DIMOND CENTER</text><route><id>2</id><name>LAKE OTIS</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:13</edt><sdt>14:13</sdt><dev>0</dev><text>2 DIMOND CENTER</text><route><id>2</id><name>LAKE OTIS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:13</edt><sdt>15:13</sdt><dev>0</dev><text>2 DIMOND CENTER</text><route><id>2</id><name>LAKE OTIS</name></route><dir>O</dir></departure></stop><stop><id>1440</id><name>BENSON and C ST</name><departure mode="destination"><edt>13:27</edt><sdt>13:26</sdt><dev>67</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:26</edt><sdt>14:26</sdt><dev>0</dev><text>3N CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:26</edt><sdt>15:26</sdt><dev>0</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure></stop><stop><id>1441</id><name>NORTHERN LIGHTS and C ST</name><departure mode="destination"><edt>13:52</edt><sdt>13:52</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:52</edt><sdt>14:52</sdt><dev>0</dev><text>3C DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:52</edt><sdt>15:52</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure></stop><stop><id>1442</id><name>CENTENNIAL VILLAGE</name><departure mode="destination"><edt>13:10</edt><sdt>13:10</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:10</edt><sdt>14:10</sdt><dev>0</dev><text>3C DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:10</edt><sdt>15:10</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure></stop><stop><id>1443</id><name>NUNAKA and DEBARR</name><departure mode="destination"><edt>13:24</edt><sdt>13:24</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:24</edt><sdt>15:24</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>17:24</edt><sdt>17:24</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:53</edt><sdt>14:53</sdt><dev>0</dev><text>3N CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>16:53</edt><sdt>16:53</sdt><dev>0</dev><text>3N CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>18:52</edt><sdt>18:52</sdt><dev>0</dev><text>3N CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure></stop><stop><id>1444</id><name>PATTERSON and NORTHERN LIGHTS</name><departure mode="destination"><edt>14:26</edt><sdt>14:26</sdt><dev>0</dev><text>3C DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>16:26</edt><sdt>16:26</sdt><dev>0</dev><text>3C DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>18:25</edt><sdt>18:25</sdt><dev>0</dev><text>3C DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:51</edt><sdt>13:50</sdt><dev>67</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:50</edt><sdt>15:50</sdt><dev>0</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>17:50</edt><sdt>17:50</sdt><dev>0</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure></stop><stop><id>1445</id><name>SPENARD and NORTHERN LIGHTS</name><departure mode="destination"><edt>13:26</edt><sdt>13:26</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:23</edt><sdt>14:23</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:26</edt><sdt>15:26</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:50</edt><sdt>13:50</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:50</edt><sdt>14:50</sdt><dev>0</dev><text>7J DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:50</edt><sdt>15:50</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure></stop><stop><id>1446</id><name>NORTHWOOD and 88TH AVE</name><departure mode="destination"><edt>13:50</edt><sdt>13:50</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:50</edt><sdt>15:50</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>17:50</edt><sdt>17:50</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:19</edt><sdt>14:19</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>16:19</edt><sdt>16:19</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>18:15</edt><sdt>18:15</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure></stop><stop><id>1447</id><name>JEWEL LAKE and 88TH AVE</name><departure mode="destination"><edt>14:53</edt><sdt>14:53</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>16:53</edt><sdt>16:53</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>18:52</edt><sdt>18:52</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:23</edt><sdt>13:19</sdt><dev>243</dev><text>7J DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:19</edt><sdt>15:19</sdt><dev>0</dev><text>7J DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>17:17</edt><sdt>17:17</sdt><dev>0</dev><text>7J DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure></stop><stop><id>1448</id><name>AIRPORT SOUTH TERMINAL</name><departure mode="destination"><edt>14:07</edt><sdt>14:07</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:10</edt><sdt>15:10</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>16:07</edt><sdt>16:07</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:06</edt><sdt>14:06</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:06</edt><sdt>15:06</sdt><dev>0</dev><text>7J DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>16:06</edt><sdt>16:06</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure></stop><stop><id>1449</id><name>BONIFACE and 4TH AVE</name><departure mode="destination"><edt>13:28</edt><sdt>13:28</sdt><dev>0</dev><text>8 DOWNTOWN</text><route><id>8</id><name>NORTHWAY</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:28</edt><sdt>14:28</sdt><dev>0</dev><text>8 DOWNTOWN</text><route><id>8</id><name>NORTHWAY</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:27</edt><sdt>15:27</sdt><dev>0</dev><text>8 DOWNTOWN</text><route><id>8</id><name>NORTHWAY</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:04</edt><sdt>14:04</sdt><dev>0</dev><text>8 MULDOON</text><route><id>8</id><name>NORTHWAY</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:04</edt><sdt>15:04</sdt><dev>0</dev><text>8 MULDOON</text><route><id>8</id><name>NORTHWAY</name></route><dir>O</dir></departure><departure mode="destination"><edt>16:05</edt><sdt>16:05</sdt><dev>0</dev><text>8 MULDOON</text><route><id>8</id><name>NORTHWAY</name></route><dir>O</dir></departure></stop><stop><id>1450</id><name>OKLAHOMA and BOUNDARY</name><departure mode="destination"><edt>13:20</edt><sdt>13:20</sdt><dev>0</dev><text>8 DOWNTOWN</text><route><id>8</id><name>NORTHWAY</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:20</edt><sdt>14:20</sdt><dev>0</dev><text>8 DOWNTOWN</text><route><id>8</id><name>NORTHWAY</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:19</edt><sdt>15:19</sdt><dev>0</dev><text>8 DOWNTOWN</text><route><id>8</id><name>NORTHWAY</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:13</edt><sdt>13:12</sdt><dev>91</dev><text>8 MULDOON</text><route><id>8</id><name>NORTHWAY</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:12</edt><sdt>14:12</sdt><dev>0</dev><text>8 MULDOON</text><route><id>8</id><name>NORTHWAY</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:12</edt><sdt>15:12</sdt><dev>0</dev><text>8 MULDOON</text><route><id>8</id><name>NORTHWAY</name></route><dir>O</dir></departure></stop><stop><id>1451</id><name>ARCTIC and INTL AIRPORT RD</name><departure mode="destination"><edt>13:49</edt><sdt>13:49</sdt><dev>0</dev><text>9 DOWNTOWN</text><route><id>9</id><name>ARCTIC</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:49</edt><sdt>14:49</sdt><dev>0</dev><text>9 DOWNTOWN</text><route><id>9</id><name>ARCTIC</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:49</edt><sdt>15:49</sdt><dev>0</dev><text>9 DOWNTOWN</text><route><id>9</id><name>ARCTIC</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:24</edt><sdt>13:21</sdt><dev>197</dev><text>9 DIMOND CENTER</text><route><id>9</id><name>ARCTIC</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:21</edt><sdt>14:21</sdt><dev>0</dev><text>9 DIMOND CENTER</text><route><id>9</id><name>ARCTIC</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:21</edt><sdt>15:21</sdt><dev>0</dev><text>9 DIMOND CENTER</text><route><id>9</id><name>ARCTIC</name></route><dir>O</dir></departure></stop><stop><id>1452</id><name>SENIOR CENTER</name><departure mode="destination"><edt>14:03</edt><sdt>14:03</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:03</edt><sdt>15:03</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>16:03</edt><sdt>16:03</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:35</edt><sdt>13:35</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:35</edt><sdt>14:35</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:35</edt><sdt>15:35</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure></stop><stop><id>1453</id><name>NORTHERN LIGHTS and BONIFACE</name><departure mode="destination"><edt>13:30</edt><sdt>13:30</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:30</edt><sdt>14:30</sdt><dev>0</dev><text>3C DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:30</edt><sdt>15:30</sdt><dev>0</dev><text>3N DOWNTOWN</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:49</edt><sdt>13:48</sdt><dev>67</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:48</edt><sdt>14:48</sdt><dev>0</dev><text>3N CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:48</edt><sdt>15:48</sdt><dev>0</dev><text>3C CENTENNIAL</text><route><id>3</id><name>NORTHERN LIGHTS</name></route><dir>O</dir></departure><departure mode="destination"><edt>13:34</edt><sdt>13:34</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:34</edt><sdt>14:34</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:34</edt><sdt>15:34</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:05</edt><sdt>14:05</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:05</edt><sdt>15:05</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>16:05</edt><sdt>16:05</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure></stop><stop><id>1454</id><name>13TH and GAMBELL</name><departure mode="destination"><edt>13:16</edt><sdt>13:13</sdt><dev>205</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:13</edt><sdt>14:13</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:13</edt><sdt>15:13</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:25</edt><sdt>13:25</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:25</edt><sdt>14:25</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:25</edt><sdt>15:25</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure></stop><stop><id>1455</id><name>BLUFF and BIRCH</name><departure mode="destination"><edt>13:56</edt><sdt>13:56</sdt><dev>0</dev><text>14 DOWNTOWN</text><route><id>14</id><name>GOVERNMENT HILL</name></route><dir>L</dir></departure><departure mode="destination"><edt>14:56</edt><sdt>14:56</sdt><dev>0</dev><text>14 DOWNTOWN</text><route><id>14</id><name>GOVERNMENT HILL</name></route><dir>L</dir></departure><departure mode="destination"><edt>15:56</edt><sdt>15:56</sdt><dev>0</dev><text>14 DOWNTOWN</text><route><id>14</id><name>GOVERNMENT HILL</name></route><dir>L</dir></departure></stop><stop><id>1456</id><name>HOLLYWOOD and LOOP</name><departure mode="destination"><edt>14:04</edt><sdt>14:04</sdt><dev>0</dev><text>14 DOWNTOWN</text><route><id>14</id><name>GOVERNMENT HILL</name></route><dir>L</dir></departure><departure mode="destination"><edt>15:04</edt><sdt>15:04</sdt><dev>0</dev><text>14 DOWNTOWN</text><route><id>14</id><name>GOVERNMENT HILL</name></route><dir>L</dir></departure><departure mode="destination"><edt>16:04</edt><sdt>16:04</sdt><dev>0</dev><text>14 DOWNTOWN</text><route><id>14</id><name>GOVERNMENT HILL</name></route><dir>L</dir></departure></stop><stop><id>1457</id><name>ALASKA REGIONAL HOSPITAL</name><departure mode="destination"><edt>13:56</edt><sdt>13:56</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:56</edt><sdt>14:56</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:56</edt><sdt>15:56</sdt><dev>0</dev><text>13 DOWNTOWN</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:41</edt><sdt>13:41</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:41</edt><sdt>14:41</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:41</edt><sdt>15:41</sdt><dev>0</dev><text>13 MULDOON</text><route><id>13</id><name>UNIVERSITY/HOSPITALS</name></route><dir>O</dir></departure><departure mode="destination"><edt>13:48</edt><sdt>13:48</sdt><dev>0</dev><text>15 DOWNTOWN</text><route><id>15</id><name>15TH AVE/DEBARR</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:48</edt><sdt>14:48</sdt><dev>0</dev><text>15 DOWNTOWN</text><route><id>15</id><name>15TH AVE/DEBARR</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:48</edt><sdt>15:48</sdt><dev>0</dev><text>15 DOWNTOWN</text><route><id>15</id><name>15TH AVE/DEBARR</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:16</edt><sdt>13:12</sdt><dev>299</dev><text>15 MULDOON</text><route><id>15</id><name>15TH AVE/DEBARR</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:12</edt><sdt>14:12</sdt><dev>0</dev><text>15 MULDOON</text><route><id>15</id><name>15TH AVE/DEBARR</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:12</edt><sdt>15:12</sdt><dev>0</dev><text>15 MULDOON</text><route><id>15</id><name>15TH AVE/DEBARR</name></route><dir>O</dir></departure></stop><stop><id>1458</id><name>MINNESOTA and N LIGHTS</name><departure mode="destination"><edt>13:31</edt><sdt>13:28</sdt><dev>220</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:28</edt><sdt>14:28</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:28</edt><sdt>15:28</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:17</edt><sdt>13:13</sdt><dev>269</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:13</edt><sdt>14:13</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:13</edt><sdt>15:13</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure></stop><stop><id>1459</id><name>SPENARD and WISCONSIN</name><departure mode="destination"><edt>13:16</edt><sdt>13:16</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:13</edt><sdt>14:13</sdt><dev>0</dev><text>7A DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:16</edt><sdt>15:16</sdt><dev>0</dev><text>7J DOWNTOWN</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:58</edt><sdt>13:58</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:58</edt><sdt>14:58</sdt><dev>0</dev><text>7J DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:58</edt><sdt>15:58</sdt><dev>0</dev><text>7A DIMOND CENTER</text><route><id>7</id><name>SPENARD/AIRPORT</name></route><dir>O</dir></departure><departure mode="destination"><edt>13:19</edt><sdt>13:16</sdt><dev>220</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:16</edt><sdt>14:16</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:16</edt><sdt>15:16</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:26</edt><sdt>13:22</sdt><dev>269</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:22</edt><sdt>14:22</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:22</edt><sdt>15:22</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure></stop><stop><id>1460</id><name>TUDOR and MINNESOTA</name><departure mode="destination"><edt>13:13</edt><sdt>13:10</sdt><dev>220</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:10</edt><sdt>14:10</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:10</edt><sdt>15:10</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:33</edt><sdt>13:29</sdt><dev>269</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:29</edt><sdt>14:29</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:29</edt><sdt>15:29</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure></stop><stop><id>1461</id><name>36TH AVE and A STREET</name><departure mode="destination"><edt>14:04</edt><sdt>14:04</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:04</edt><sdt>15:04</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>16:04</edt><sdt>16:04</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>13:39</edt><sdt>13:35</sdt><dev>269</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>14:35</edt><sdt>14:35</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure><departure mode="destination"><edt>15:35</edt><sdt>15:35</sdt><dev>0</dev><text>36 APU</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>O</dir></departure></stop><stop><id>1462</id><name>ALASKA PACIFIC UNIVERSITY</name><departure mode="destination"><edt>13:54</edt><sdt>13:54</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:54</edt><sdt>14:54</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure><departure mode="destination"><edt>15:54</edt><sdt>15:54</sdt><dev>0</dev><text>36 DOWNTOWN</text><route><id>36</id><name>WEST ANCHORAGE/U-MED</name></route><dir>I</dir></departure></stop><stop><id>1463</id><name>BRAGAW and MT. VIEW</name><departure mode="destination"><edt>13:30</edt><sdt>13:30</sdt><dev>0</dev><text>45 DOWNTOWN</text><route><id>45</id><name>MOUNTAIN VIEW</name></route><dir>I</dir></departure><departure mode="destination"><edt>14:30</edt><sdt>14:30</sdt><dev>0</dev><