<?xml version="1.0"?>
<!DOCTYPE vehicle-locations [
<!ELEMENT vehicle-locations (report-generated, vehicle*)>
	<!ELEMENT report-generated (#PCDATA)>
		<!-- timezone is an integer between -12 and 12 inclusive. -->
       <!-- the timezone is reference to GMT and is -5 for Acadia. -->
		<!ATTLIST report-generated timezone CDATA #REQUIRED>
	<!ELEMENT vehicle (name, routeid, tripid, runid*, destination*, direction, laststop, latitude, longitude, speed, heading)>
		<!ATTLIST vehicle op-status (on-time|late|early|out-of-service|special|none) #REQUIRED>
		<!ATTLIST vehicle comm-status (good|unknown) #REQUIRED>
		<!ATTLIST vehicle gps-status (good|bad|unknown) #REQUIRED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT routeid (#PCDATA)>
		<!ELEMENT tripid (#PCDATA)>
		<!ELEMENT runid (#PCDATA)>
		<!ELEMENT destination (#PCDATA)>
		<!ELEMENT direction (#PCDATA)> <!-- I, O, or L -->
		<!ELEMENT laststop (#PCDATA)>
 		<!ELEMENT latitude (#PCDATA)>
		<!ELEMENT longitude (#PCDATA)>
		<!ELEMENT speed (#PCDATA)>
			<!ATTLIST speed units (mph|kph) "mph">
		<!ELEMENT heading (#PCDATA)>
]>

<vehicle-locations><report-generated timezone="-9">2015-09-19 16:12</report-generated><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>12345</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60201</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60202</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60203</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60204</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60205</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60206</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60207</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60208</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60209</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60210</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60211</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60212</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17775</latitude><longitude>-149.81215</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60213</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60214</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60215</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60216</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60217</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81354</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60218</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60219</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81418</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60220</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.21845</latitude><longitude>-149.8778</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60221</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.8125</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60222</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1976</latitude><longitude>-149.74507</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60223</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.812</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60224</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60225</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17758</latitude><longitude>-149.81218</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60226</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17895</latitude><longitude>-149.8683</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60227</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.154034</latitude><longitude>-149.83435</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60228</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.180866</latitude><longitude>-149.79668</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60229</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60230</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81302</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60231</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.210716</latitude><longitude>-149.73326</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60232</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177883</latitude><longitude>-149.81378</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60233</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177567</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60234</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60235</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177784</latitude><longitude>-149.81384</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60236</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60237</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17775</latitude><longitude>-149.81381</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60238</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60239</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.215614</latitude><longitude>-149.89667</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60240</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.134132</latitude><longitude>-149.86382</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60241</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.2324</latitude><longitude>-149.74362</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60242</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81409</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60243</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60244</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8128</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60245</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177917</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60246</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60247</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81253</longitude><speed>0</speed><heading>36</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60248</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81256</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60249</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60250</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177567</latitude><longitude>-149.8125</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60251</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1783</latitude><longitude>-149.81215</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60257</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1784</latitude><longitude>-149.81456</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60260</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177483</latitude><longitude>-149.81218</longitude><speed>2</speed><heading>12</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60261</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60263</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81406</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60267</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81447</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60268</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81241</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60270</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1784</latitude><longitude>-149.81418</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60271</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17758</latitude><longitude>-149.8127</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60272</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178116</latitude><longitude>-149.81183</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60273</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1776</latitude><longitude>-149.8127</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60292</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81433</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60293</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81401</longitude><speed>8</speed><heading>266</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60294</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60295</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1784</latitude><longitude>-149.81343</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="good"><name>60296</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8144</longitude><speed>2</speed><heading>266</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60297</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1783</latitude><longitude>-149.81447</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60298</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81436</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60299</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81456</longitude><speed>2</speed><heading>288</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60300</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.81433</longitude><speed>2</speed><heading>264</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="good"><name>60301</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178234</latitude><longitude>-149.81305</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60302</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8144</longitude><speed>2</speed><heading>272</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63001</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63002</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63003</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177315</latitude><longitude>-149.81357</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63004</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63005</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1779</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>Test</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name></name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="good"><name>60275</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>56</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60277</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60284</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177334</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60286</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177483</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60287</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>42</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60289</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60290</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1776</latitude><longitude>-149.81273</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60279</name><routeid>1</routeid><tripid>1531</tripid><runid>215</runid><destination>1 MULDOON</destination><direction>I</direction><laststop>MULDOON and DEBARR EAST</laststop><latitude>61.210632</latitude><longitude>-149.73323</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60256</name><routeid>1</routeid><tripid>1520</tripid><runid>221</runid><destination>1 DIMOND CENTER</destination><direction>O</direction><laststop>DIMOND TRANSIT CENTER</laststop><latitude>61.1424</latitude><longitude>-149.87218</longitude><speed>13</speed><heading>174</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60266</name><routeid>2</routeid><tripid>1607</tripid><runid>228</runid><destination>2 DOWNTOWN</destination><direction>I</direction><laststop>OLD SEWARD and 88TH AVENUE SSW</laststop><latitude>61.1323</latitude><longitude>-149.864</longitude><speed>17</speed><heading>180</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60285</name><routeid>2</routeid><tripid>1542</tripid><runid>206</runid><destination>2 DIMOND CENTER</destination><direction>O</direction><laststop>LAKE OTIS and PAGO PAGO NNW: 0030</laststop><latitude>61.159317</latitude><longitude>-149.83435</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60274</name><routeid>3</routeid><tripid>1610</tripid><runid>214</runid><destination>3C DOWNTOWN</destination><direction>I</direction><laststop>CENTENNIAL VILLAGE</laststop><latitude>61.224667</latitude><longitude>-149.7169</longitude><speed>22</speed><heading>238</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60264</name><routeid>3</routeid><tripid>1510</tripid><runid>201</runid><destination>3N DOWNTOWN</destination><direction>I</direction><laststop>NORTHERN LIGHTS and LATOUCHE WNW: 0401</laststop><latitude>61.195282</latitude><longitude>-149.86737</longitude><speed>22</speed><heading>270</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60269</name><routeid>7</routeid><tripid>1540</tripid><runid>224</runid><destination>7A DOWNTOWN</destination><direction>I</direction><laststop>INTERNATIONAL ARPT and RR XING WSW: 3033</laststop><latitude>61.173767</latitude><longitude>-149.94395</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60252</name><routeid>7</routeid><tripid>1538</tripid><runid>226</runid><destination>7A DIMOND CENTER</destination><direction>O</direction><laststop>OLD INTL AIR and 4100 S</laststop><latitude>61.1593</latitude><longitude>-149.95195</longitude><speed>38</speed><heading>180</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60262</name><routeid>8</routeid><tripid>1539</tripid><runid>225</runid><destination>8 MULDOON</destination><direction>O</direction><laststop></laststop><latitude>61.215115</latitude><longitude>-149.75584</longitude><speed>29</speed><heading>358</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60278</name><routeid>9</routeid><tripid>1604</tripid><runid>230</runid><destination>9 DIMOND CENTER</destination><direction>O</direction><laststop>E STREET and 12TH AVENUE SSW: 0654</laststop><latitude>61.21028</latitude><longitude>-149.89143</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60282</name><routeid>13</routeid><tripid>1517</tripid><runid>229</runid><destination>13 MULDOON</destination><direction>O</direction><laststop>NORTHERN LIGHTS and BONIFACE</laststop><latitude>61.195217</latitude><longitude>-149.73827</longitude><speed>38</speed><heading>90</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60254</name><routeid>13</routeid><tripid>1527</tripid><runid>213</runid><destination>13 DOWNTOWN</destination><direction>I</direction><laststop>SENIOR CENTER</laststop><latitude>61.213615</latitude><longitude>-149.86656</longitude><speed>6</speed><heading>270</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60281</name><routeid>14</routeid><tripid>1551</tripid><runid>227</runid><destination>14 DOWNTOWN</destination><direction>L</direction><laststop>C STREET and 7TH AVENUE SSW: 0003</laststop><latitude>61